### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by bla-bu** [yahoo/egads#39]
Hi,

Did you consider maybe releasing egads under different, less restrictive, license (preferably Apache)? The reason I’m asking is that right now, at least for me, egads is more like a library that I can plug into my code rather then “a tool”. And obviously, current GPL license, is problematic from this PoV.

Thanks

**Comment by ricardojlrufino** [comment]
I think the most appropriate would be LGPL

**Comment by ricardojlrufino** [comment]
Like: https://github.com/etheriau/OpenForecast , used by this

**Comment by manolama** [comment]
Let me check with our OSS team, maybe we can use Apache.

**Comment by gyehuda** [comment]
We were required to use GPL instead of a more permissive option because the project developers copied existing GPL code and pasted it into the project. Refactoring that code out of this project would allow us to relicense the code under more permissive terms (e.g. the Apache license). Let me know if you'll do this and I'll be glad to help with the details.

**Comment by cyrilou242** [comment]
Hey @gyehuda, 
I'd be interested in knowing the GPL code files/parts necessary to rewrite/refactor out.

**Comment by manolama** [comment]
@cyrilou242 
Looks like any file with a header starting with ``OpenForecast - open source, general-purpose forecasting package`` may have some GPL'd bits from OpenForecast that were pulled in. And it may just be the models in https://github.com/yahoo/egads/tree/master/src/main/java/com/yahoo/egads/models/tsmm. Refactoring all of that would clean up the license.

**Comment by cyrilou242** [comment]
thanks @manolama I'll have a look and try to estimate the work needed
